RK_device_platform: RK3562
# RK_device_id: simulator
model_framework: onnx
model_file_path: ./model_file/lite-transformer-decoder-16.onnx
quantize: False
dataset: ./decoder_dataset.txt

graph:
  in_0:
    shape: 1,1,256
  in_1:
    shape: 1,16,256
  in_2:
    shape: 16
  in_3:
    shape: 16
  in_4:
    shape: 1,4,15,64
  in_5:
    shape: 1,4,15,64
  in_6:
    shape: 1,4,15,64
  in_7:
    shape: 1,4,15,64
  in_8:
    shape: 1,4,15,64
  in_9:
    shape: 1,4,15,64


configs:
  # quantized_dtype: dynamic_fixed_point-i16
  quantized_algorithm: normal
  optimization_level: 3
  do_sparse_network: True
  # remove_weight: True
